device: cuda:3
sparse: True
lr: 0.001
epochs: 500
eval_freq: 50000
data:
    train_file: "/home/apd10/ExtremeClassificationRz/data/LF-AmazonTitles-131K/train.txt"
    test_file: "/home/apd10/ExtremeClassificationRz/data/LF-AmazonTitles-131K/test.txt"
    train_batch: 128
    test_batch: 128
    dimension: 40000
    label_dimension: 131073
 
model:
    rz: False
    arch: 40000-500-500-131073
