device: cuda:2
epochs: 10
eval_freq: 1000
data:
    train_file: "/home/apd10/ExtremeClassificationRz/data/LF-AmazonTitles-131K/train.txt"
    test_file: "/home/apd10/ExtremeClassificationRz/data/LF-AmazonTitles-131K/test.txt.x"
    train_batch: 128
    test_batch: 128
    dimension: 40000
    label_dimension: 131073
 
model:
    rz: True
    arch: 40000-100-131073
    sizes: [40000, 100000]
